#!/bin/bash
# qsub -l cpu_arch=x86_64 matlab-test.job
# The name of the job, can be anything, simply used when displaying the list of running jobs
#$ -N matlab-test
# Giving the name of the output log file
#$ -o matlabTest.log
# Combining output/error messages into one file
#$ -j y
# One needs to tell the queue system to use the current directory as the working directory
# Or else the script may fail as it will execute in your top level home directory /home/username
#$ -cwd
# Now comes the commands to be executed
#/share/apps/matlab/bin/matlab -nodisplay -nodesktop -nojvm -r matlab-test
/usr/local/bin/matlab -nodisplay -nodesktop -nojvm << EOF
version
disp('$1');
EOF
# Note after -r is not the name of the m-file but the name of the routine
exit 0
